import Link from "next/link";
import type {Tool} from "@/data/tools";
const descriptions:Record<string,{intro:string;how:string;formula:string;example:string;understanding:string;mistakes:string;faq:string[]}> = {
 "ohms-law-calculator":{intro:"Ohm's Law relates voltage, current and resistance in an electrical circuit. This calculator can solve the missing electrical quantity from known values.",how:"Enter at least two compatible electrical values, then select Calculate. Use positive numeric values.",formula:"V = I × R; P = V × I",example:"For 12 V and 2 A, resistance is 6 Ω and power is 24 W.",understanding:"Voltage is electrical potential difference, current is charge flow, and resistance describes opposition to current.",mistakes:"Do not divide by zero and check that units are consistent.",faq:["What is Ohm's Law?","Can I calculate resistance from voltage and current?"]},
 "electricity-bill-calculator":{intro:"Estimate electricity consumption and cost from appliance power and usage. The tariff is user-configurable because electricity rates can vary by tariff, location and time.",how:"Enter appliance power, quantity, hours per day, days per month and your applicable tariff.",formula:"Energy(kWh) = Power(kW) × Quantity × Hours × Days; Cost = Energy × Tariff",example:"A 100 W device used 5 hours/day for 30 days consumes 15 kWh/month.",understanding:"The estimate is a consumption model, not a utility bill. Actual billing can include tariff structure, taxes and other charges.",mistakes:"Use input power rather than only a marketing cooling capacity when estimating an appliance's electricity consumption.",faq:["Does this use a current PLN tariff?","Why can my actual bill differ?"]},
 "solar-panel-calculator":{intro:"Estimate solar PV capacity from daily energy demand, peak sun hours and an assumed system efficiency.",how:"Enter daily energy demand, peak sun hours for the location and an overall efficiency assumption.",formula:"PV capacity = Daily energy ÷ (Peak sun hours × Efficiency)",example:"If demand is 5 kWh/day, peak sun hours are 4 and efficiency is 80%, the estimate is about 1.56 kWp.",understanding:"Peak sun hours and system efficiency are simplifications. Weather, orientation, shading, temperature and equipment losses affect real output.",mistakes:"Do not treat the result as a final electrical design without site-specific analysis.",faq:["What are peak sun hours?","Why is system efficiency below 100%?"]},
 "cable-size-calculator":{intro:"Estimate conductor cross-section using a voltage-drop criterion. The result is a starting point and does not replace ampacity, installation-method, temperature and code checks.",how:"Enter current, one-way length, voltage and allowable voltage drop. Choose copper or aluminum.",formula:"A = 2 × L × I × ρ ÷ Vdrop",example:"A larger current or longer cable requires a larger conductor cross-section for the same allowable voltage drop.",understanding:"Voltage drop is only one cable-sizing criterion. Thermal ampacity and applicable electrical standards must also be checked.",mistakes:"Do not select a final cable solely from voltage drop; verify ampacity and local code requirements.",faq:["Does this calculate ampacity?","Why is cable length one-way?"]},
 "voltage-drop-calculator":{intro:"Estimate cable voltage loss from current, cable length and cable resistance.",how:"Enter supply voltage, current, one-way cable length and resistance in ohms per kilometre.",formula:"Vdrop = I × R × loop length; Vload = Vsupply − Vdrop",example:"For a two-wire DC circuit, the return conductor contributes to the loop length.",understanding:"The result depends strongly on the resistance value and cable temperature.",mistakes:"Make sure the resistance unit is Ω/km and the length is entered in metres.",faq:["Does the calculator include the return conductor?","Can I use it for AC?"]},
 "electrical-power-calculator":{intro:"Electrical power depends on voltage, current and, for AC loads, power factor and phase arrangement.",how:"Choose DC, single-phase AC or three-phase AC, then enter voltage, current and power factor where applicable.",formula:"DC: P = V × I. Single phase: P = V × I × PF. Three phase: P = √3 × V × I × PF.",example:"At 230 V and 10 A with PF 0.8 on single phase, active power is 1.84 kW.",understanding:"Power factor represents the ratio of real power to apparent power for an AC load.",mistakes:"Do not use a three-phase formula for a single-phase circuit.",faq:["When should I enter power factor?","What is the difference between kW and kVA?"]},
 "voltage-divider-calculator":{intro:"A resistor voltage divider produces a fraction of an input voltage using two series resistors.",how:"Enter Vin, R1 and R2. R1 is the upper resistor and R2 is the lower resistor in the standard divider.",formula:"Vout = Vin × R2 ÷ (R1 + R2)",example:"With Vin 12 V, R1 1 kΩ and R2 1 kΩ, Vout is 6 V.",understanding:"The divider assumes the output load does not significantly change the resistor ratio.",mistakes:"Do not swap R1 and R2 when comparing your circuit to the diagram or formula.",faq:["Which resistor is R1?","Does load resistance affect a voltage divider?"]},
 "three-phase-power-calculator":{intro:"Three-phase power calculations are useful for motors, industrial loads and distribution systems.",how:"Enter line voltage, current and power factor for the balanced-load estimate.",formula:"S = √3 × V × I; P = S × PF; Q = √(S² − P²)",example:"At 400 V, 10 A and PF 0.8, active power is about 5.54 kW.",understanding:"The calculation assumes a balanced three-phase system and line-to-line voltage.",mistakes:"Confirm whether your voltage measurement is line-to-line or line-to-neutral.",faq:["Does this use line voltage?","What is reactive power?"]},
 "power-factor-calculator":{intro:"Power factor compares real power used by a load with its apparent power.",how:"Enter real power in watts and apparent power in VA.",formula:"PF = P ÷ S",example:"A 4 kW load with 5 kVA apparent power has PF 0.8.",understanding:"A lower power factor means more current is required for the same real power.",mistakes:"Apparent power must not be smaller than real power for a normal passive AC load.",faq:["Can power factor exceed 1?","Why does power factor matter?"]},
 "kwh-cost-calculator":{intro:"The kWh cost calculator estimates energy consumption and electricity cost from appliance power and operating time.",how:"Enter the rated input power, quantity, daily hours, monthly days and the tariff you want to model.",formula:"Monthly kWh = Power(W) × Quantity × Hours × Days ÷ 1000",example:"A 500 W appliance used 4 hours/day for 30 days consumes 60 kWh.",understanding:"The result is an estimate based on the power input you provide and the tariff you enter.",mistakes:"Do not confuse appliance cooling capacity or mechanical output with electrical input power.",faq:["What tariff should I enter?","Why does the estimate differ from my bill?"]},
 "battery-runtime-calculator":{intro:"Battery runtime depends on stored energy, load power and usable battery efficiency.",how:"Choose Ah or Wh capacity, enter voltage when using Ah, then enter load and efficiency.",formula:"Energy(Wh) = Voltage × Ah; Runtime = Energy × Efficiency ÷ Load",example:"A 12 V 100 Ah battery contains about 1.2 kWh before losses.",understanding:"Actual runtime changes with discharge rate, temperature, battery age and the usable state-of-charge range.",mistakes:"Do not assume the nameplate Ah capacity is fully usable energy.",faq:["Why do I need voltage in Ah mode?","Does this account for battery aging?"]},
 "unit-converter":{intro:"Engineering work frequently requires quick conversion between SI and common technical units.",how:"Choose a category, source unit, destination unit and value, then select Convert.",formula:"Converted value = Input × source factor ÷ destination factor. Temperature uses Kelvin as the conversion reference.",example:"1 kW equals 1000 W and 1 kWh equals 3.6 MJ.",understanding:"Unit conversion changes representation without changing the physical quantity.",mistakes:"Do not use area or energy conversion factors for length or power.",faq:["Does it support temperature?","Which units are supported?"]},
 "resistor-color-code-calculator":{intro:"Through-hole resistors commonly use colored bands to encode resistance and tolerance.",how:"Choose 4, 5 or 6 bands and select each band color. The decoder calculates resistance and tolerance.",formula:"Resistance = significant digits × multiplier",example:"Brown-black-red-gold corresponds to 1 kΩ with 5% tolerance.",understanding:"Four-band resistors use two significant digits, while five- and six-band resistors use three.",mistakes:"Read the bands from the correct orientation and do not treat tolerance as a multiplier.",faq:["What does the gold band mean?","What does the sixth band represent?"]},
 "solar-battery-calculator":{intro:"Battery storage sizing links daily energy demand with the number of days of autonomy and the usable battery fraction.",how:"Enter daily energy, desired autonomy, depth of discharge and system efficiency.",formula:"Battery capacity = Daily energy × Autonomy ÷ (DoD × Efficiency)",example:"Higher autonomy increases the required nominal battery capacity.",understanding:"DoD and efficiency protect against assuming that all nameplate battery energy is usable.",mistakes:"A battery bank should also be checked for voltage, maximum current and manufacturer limits.",faq:["What is depth of discharge?","Why include efficiency?"]},
 "motor-current-calculator":{intro:"Motor current can be estimated from output power, voltage, power factor and efficiency.",how:"Choose single- or three-phase operation and enter motor output power, voltage, PF and efficiency.",formula:"Three phase: I = P ÷ (√3 × V × PF × η)",example:"A 5 kW, 400 V, PF 0.85, 90% efficient three-phase motor draws roughly 9.43 A.",understanding:"Nameplate current can differ because real motors have specific design and operating conditions.",mistakes:"Do not use this estimate as a substitute for the motor nameplate or protection coordination.",faq:["Should I use motor input or output power?","Why does efficiency affect current?"]},
 "transformer-calculator":{intro:"An ideal transformer relates primary and secondary voltage to turns ratio and apparent power to winding current.",how:"Enter primary and secondary voltage. Optional turns and kVA inputs add ratio and current results.",formula:"Vp/Vs ≈ Np/Ns; I = S/V",example:"A 230 V to 24 V transformer has a voltage ratio of about 9.58:1.",understanding:"Real transformers have losses, regulation, magnetizing current and temperature effects.",mistakes:"Do not use ideal ratios as a complete transformer design.",faq:["What is turns ratio?","How is transformer current estimated?"]},
 "generator-sizing-calculator":{intro:"Generator sizing can be expressed in kVA because generator capacity is tied to apparent power.",how:"Enter connected load in kW, expected power factor and a design margin.",formula:"Generator kVA = Load kW ÷ PF × (1 + Margin)",example:"An 80 kW load at PF 0.8 with 20% margin gives an estimate of 120 kVA.",understanding:"Starting currents, nonlinear loads, altitude, temperature and transient requirements may require additional analysis.",mistakes:"Do not size a generator from steady-state kW alone when large motors are present.",faq:["Why is generator rating in kVA?","What does the margin represent?"]},
 "ac-power-consumption-calculator":{intro:"This tool estimates monthly electrical energy from the input power and operating schedule of an air conditioner or other appliance.",how:"Enter actual electrical input power, hours per day, days per month and quantity.",formula:"Monthly kWh = Input power(kW) × Hours × Days × Quantity",example:"A 1000 W appliance operating 5 hours/day for 30 days uses about 150 kWh.",understanding:"Actual AC consumption can vary as compressors cycle and operating conditions change.",mistakes:"Do not assume a unit's cooling capacity in BTU/h is the same as its electrical input power.",faq:["Should I use rated input power?","Does inverter AC change the calculation?"]},
 "watt-to-kwh-calculator":{intro:"Watts describe power while kilowatt-hours describe accumulated energy over time.",how:"Enter power in watts and the number of operating hours and days.",formula:"Energy(kWh) = Power(W) × Hours × Days ÷ 1000",example:"A 100 W device used for 5 hours consumes 0.5 kWh.",understanding:"The calculator assumes the stated power remains constant throughout the operating period.",mistakes:"Do not interpret watts as energy consumption without a time period.",faq:["How many watts are in a kilowatt?","How does time affect kWh?"]},
};
const fallback={intro:"This engineering calculator provides a transparent estimate using the formula shown below.",how:"Enter the required values and select Calculate. Check units and use realistic inputs.",formula:"The formula used is shown in the calculation result.",example:"Try a simple set of positive values and compare the result with a manual calculation.",understanding:"Calculator results are mathematical estimates based on the inputs and assumptions described on this page.",mistakes:"Check units, decimal separators and assumptions before using the result.",faq:["How is the result calculated?","Can I use this result for a final engineering design?"]};
export default function ToolContent({tool,related}:{tool:Tool;related:Tool[]}){
 const d=descriptions[tool.slug]||fallback;
 return <div className="mt-8 space-y-8">
  <section><h2 className="text-2xl font-semibold">What is {tool.name.replace(" Calculator","")}?</h2><p className="mt-2 leading-7 text-slate-700 dark:text-slate-300">{d.intro}</p></section>
  <section><h2 className="text-2xl font-semibold">How to use this calculator</h2><p className="mt-2 leading-7 text-slate-700 dark:text-slate-300">{d.how}</p></section>
  <section><h2 className="text-2xl font-semibold">Formula</h2><p className="mt-2 rounded-xl bg-slate-50 p-4 font-mono dark:bg-slate-800">{d.formula}</p></section>
  <section><h2 className="text-2xl font-semibold">Example calculation</h2><p className="mt-2 leading-7 text-slate-700 dark:text-slate-300">{d.example}</p></section>
  <section><h2 className="text-2xl font-semibold">Understanding the result</h2><p className="mt-2 leading-7 text-slate-700 dark:text-slate-300">{d.understanding}</p></section>
  <section><h2 className="text-2xl font-semibold">Common mistakes</h2><p className="mt-2 leading-7 text-slate-700 dark:text-slate-300">{d.mistakes}</p></section>
  <section><h2 className="text-2xl font-semibold">FAQ</h2><div className="mt-3 space-y-4">{d.faq.map(q=><details key={q} className="rounded-xl border p-4 dark:border-slate-700"><summary className="cursor-pointer font-medium">{q}</summary><p className="mt-2 text-slate-600 dark:text-slate-300">Use the inputs and formula shown on this page. For safety-critical or regulated work, verify the result against applicable standards and manufacturer documentation.</p></details>)}</div></section>
  {related.length>0&&<section><h2 className="text-2xl font-semibold">Related calculators</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{related.map(r=><Link key={r.slug} href={`/tools/${r.slug}`} className="rounded-xl border p-4 hover:border-blue-500 dark:border-slate-700"><strong>{r.name}</strong><p className="mt-1 text-sm text-slate-500">{r.description}</p></Link>)}</div></section>}
  <p className="border-t pt-5 text-xs text-slate-500 dark:border-slate-700">Engineering calculators are provided for educational and estimation purposes. Critical engineering decisions should be verified using applicable standards, datasheets, manufacturer documentation and qualified professionals.</p>
 </div>;
}
