"use client";
import {useMemo,useState} from "react";
import {UNITS,convert} from "@/lib/calculators/converter";
const input="w-full rounded-lg border border-slate-300 bg-white px-3 py-3 dark:border-slate-600 dark:bg-slate-800";
export default function UnitConverter(){
 const [cat,setCat]=useState("length"),[from,setFrom]=useState("m"),[to,setTo]=useState("ft"),[value,setValue]=useState("1"),[result,setResult]=useState<number|null>(null),[error,setError]=useState("");
 const units=useMemo(()=>Object.keys(UNITS[cat]||{}),[cat]);
 function categoryChange(c:string){setCat(c);const u=Object.keys(UNITS[c]);setFrom(u[0]);setTo(u[1]||u[0]);setResult(null)}
 function calc(){const r=convert(cat,Number(value.replace(",",".")),from,to);if(r.ok){setResult(r.lines[0].value);setError("")}else{setResult(null);setError(r.error)}}
 return <div className="rounded-2xl border p-5 shadow-sm dark:border-slate-700"><div className="grid gap-4 md:grid-cols-4"><label className="text-sm font-medium">Category<select value={cat} onChange={e=>categoryChange(e.target.value)} className={input}>{Object.keys(UNITS).map(c=><option key={c} value={c}>{c}</option>)}</select></label><label className="text-sm font-medium">From<select value={from} onChange={e=>setFrom(e.target.value)} className={input}>{units.map(u=><option key={u}>{u}</option>)}</select></label><label className="text-sm font-medium">To<select value={to} onChange={e=>setTo(e.target.value)} className={input}>{units.map(u=><option key={u}>{u}</option>)}</select></label><label className="text-sm font-medium">Value<input value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" className={input}/></label></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={calc} className="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white">Convert</button><button type="button" onClick={()=>{setFrom(to);setTo(from);setResult(null)}} className="rounded-lg border px-5 py-3">Swap</button><button type="button" onClick={()=>{setValue("1");setResult(null);setError("")}} className="rounded-lg border px-5 py-3">Reset</button></div>{error&&<p role="alert" className="mt-4 text-red-600">{error}</p>}{result!==null&&<div className="mt-5 rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs uppercase text-slate-500">Result</p><p className="text-3xl font-bold">{new Intl.NumberFormat("id-ID",{maximumSignificantDigits:8}).format(result)} {to}</p><button type="button" className="mt-3 rounded-lg border px-4 py-2" onClick={()=>void navigator.clipboard.writeText(String(result))}>Copy Result</button></div>}</div>
}
